name: portal-municipal
services:
  - name: portal-municipal
    type: web
    ports:
      - port: 3000
        protocol: http
    routes:
      - path: /
        port: 3000
    regions:
      - fra
    build:
      type: nixpacks
    run:
      command: npm start
